name: pc-separation

channels:
  - defaults
  - conda-forge
  - pytorch

dependencies:
  - python>=3.8.*
  - pip
  - numpy<1.24.0
  - scipy
  - matplotlib
  - ipython
  - jupyter
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio

  - pip:
    - librosa
    - synctoolbox>=1.3.2
    - madmom
    - libfmp
    - libtsm
    - mir-eval
    - pysoundfile
    - asteroid
    - mmap_ninja
    - diffq
    - omegaconf
    - gdown
